### ISSUE TITLE
Jumping of the window

### ISSUE THREAD

**Issue by Jimmy2004** [abae/Game-Off-2019#1]
The game window fly away as I drag it. It jumps from the left bottom to the very left top and I cannot drag it any more. 
The display of my screen is 3840x2400, does it have something to do with the issue?

**Comment by abae** [comment]
Thanks for checking out my game. Unfortunately, the game only supports 1920x1080. I think on bigger resolutions it's possible to play on the 1920x1080 top left of the screen because of how it's been coded but it's unintended and may produce bugs as you describe.
